### ISSUE TITLE
"Invalid response" on https://anubis.techaro.lol/blog/release/v1.20.0/ using Fennec 141.0.0

### ISSUE THREAD

**Issue by horazont** [TecharoHQ/anubis#954]
Apologies if this isn't a great way to report that.

The blog post at https://anubis.techaro.lol/blog/release/v1.20.0/ as well as presumably other pages on https://anubis.techaro.lol/ ("Go home" also fails) end up with "Invalid response." on Fennec (mobile Firefox) 141.0.0 from F-Droid. Reloading does not help.

I'm not sure what else to report or what kind of further info from the client side could be useful.

**Comment by Xe** [comment]
This should be fixed by #944

**Comment by horazont** [comment]
Ugh, damn, I saw the #944 linked in #932 , but didn't click through because #932 was about chrome, too.

Thanks!

**Comment by Xe** [comment]
No prob, I know about the issue and am trying to fix it.

**Comment by ell1e** [comment]
I still see this a lot with various desktop browsers, on various different and completely independent sites using Anubis. Often it goes away and the site is working again after a few hours. Is this the same bug and people likely haven't updated yet, or should I file something separate? Last time I saw this was just today on  https://code.ffmpeg.org and the page says it's Anubis v1.21.3.

**Comment by Xe** [comment]
I think this has been fixed in the main branch. I'm contacting the ffmpeg people to test the version on main. If that works I'll prepare a release.

**Comment by ell1e** [comment]
Thank you for your amazing work. Anubis rocks.

**Comment by thess** [comment]
FWIW -- I don't think this problem as well as #932 is really fixed. I am running the latest version built from source and see a lot of errors as this in today's logs:

>... "err":"challenge: error when processing challenge: validate: challenge: field has invalid format: nonce: strconv.Atoi: parsing \\"24.5\\": invalid syntax"

Where does the non-integer `nonce` come from. Is it possible this is some artifact from a bad-actor or a subtle bug in the embedded javascript.

OTOH -- I may be just wrong.

**Comment by viernullvier** [comment]
@thess You've been right after all - there is indeed a subtle bug in the JS which causes the nonce to be non-integer, but only on some machines and only half the time: See #1043 and #1045.
